import "../globals.css";
// NOTE: Removed unused 'hasLocale', 'routing', and 'notFound' imports
import { NextIntlClientProvider } from "next-intl"; 
import { AuthProvider } from '../../context/userContext';
import Navbar from "../../components/app/Navbar";
import { Toaster } from "@/components/ui/sonner";



// --- METADATA ---
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// --- LAYOUT COMPONENT ---
// The function now only accepts 'children' as prop.
export default function LocaleLayout({ children }) {
  
  // The logic for accessing locale and validation has been removed.
 
  return (
    // WARNING: Since 'locale' is no longer available, 'lang' attribute is empty. 
    // This may cause issues if not set correctly in your i18n setup.
    <html lang=""> 
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className="dark"
      >
        <NextIntlClientProvider>
          <AuthProvider>
            <Navbar />
            {children}
            <Toaster />
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}